/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : EmployeeId,
  'status' : Status,
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'department' : string,
  'avatar' : string,
}
export interface EmployeeDetails {
  'traits' : Array<string>,
  'info' : Employee,
  'swot' : SWOT,
  'performance' : Performance,
  'problems' : Array<string>,
}
export type EmployeeId = bigint;
export interface Feedback {
  'id' : bigint,
  'date' : bigint,
  'description' : string,
  'employeeId' : EmployeeId,
  'category' : string,
  'severity' : Severity,
}
export interface Performance {
  'opsScore' : bigint,
  'employeeId' : EmployeeId,
  'reviewCount' : bigint,
  'salesScore' : bigint,
}
export interface SWOT {
  'weaknesses' : Array<string>,
  'strengths' : Array<string>,
  'threats' : Array<string>,
  'opportunities' : Array<string>,
  'employeeId' : EmployeeId,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Status = { 'active' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  'getActiveEmployeeCount' : ActorMethod<[], bigint>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getEmployeeDetails' : ActorMethod<[EmployeeId], EmployeeDetails>,
  'getFeedbackByEmployee' : ActorMethod<[EmployeeId], Array<Feedback>>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];