/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeId = IDL.Nat;
export const AttendanceRecordInput = IDL.Record({
  'lapseType' : IDL.Text,
  'date' : IDL.Int,
  'employeeId' : EmployeeId,
  'reason' : IDL.Text,
  'daysOff' : IDL.Nat,
});
export const SWOTInput = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'onHold' : IDL.Null,
});
export const EmployeeInput = IDL.Record({
  'region' : IDL.Text,
  'status' : Status,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'fseCategory' : IDL.Text,
  'department' : IDL.Text,
  'familyDetails' : IDL.Text,
  'pastExperience' : IDL.Vec(IDL.Text),
  'avatar' : IDL.Text,
  'fiplCode' : IDL.Text,
});
export const PerformanceInput = IDL.Record({
  'operationalDiscipline' : IDL.Nat,
  'softSkillsScore' : IDL.Nat,
  'productKnowledgeScore' : IDL.Nat,
  'salesInfluenceIndex' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const EmployeeFullInput = IDL.Record({
  'swotAnalysis' : SWOTInput,
  'employeeInfo' : EmployeeInput,
  'traits' : IDL.Vec(IDL.Text),
  'performance' : PerformanceInput,
  'problems' : IDL.Vec(IDL.Text),
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FeedbackInput = IDL.Record({
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'category' : IDL.Text,
  'severity' : Severity,
});
export const IssueSuggestionInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const SalesRecordInput = IDL.Record({
  'totalSalesAmount' : IDL.Nat,
  'accessories' : IDL.Nat,
  'employeeId' : EmployeeId,
  'extendedWarranty' : IDL.Nat,
  'fiplCode' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'region' : IDL.Text,
  'status' : Status,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'fseCategory' : IDL.Text,
  'department' : IDL.Text,
  'familyDetails' : IDL.Text,
  'pastExperience' : IDL.Vec(IDL.Text),
  'avatar' : IDL.Text,
  'fiplCode' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'category' : IDL.Text,
  'severity' : Severity,
});
export const IssueSuggestion = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'lapseType' : IDL.Text,
  'date' : IDL.Int,
  'employeeId' : EmployeeId,
  'reason' : IDL.Text,
  'daysOff' : IDL.Nat,
});
export const SWOT = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
  'employeeId' : EmployeeId,
});
export const Performance = IDL.Record({
  'operationalDiscipline' : IDL.Nat,
  'softSkillsScore' : IDL.Nat,
  'productKnowledgeScore' : IDL.Nat,
  'salesInfluenceIndex' : IDL.Nat,
  'employeeId' : EmployeeId,
  'reviewCount' : IDL.Nat,
});
export const EmployeeDetails = IDL.Record({
  'traits' : IDL.Vec(IDL.Text),
  'info' : Employee,
  'swot' : SWOT,
  'performance' : Performance,
  'problems' : IDL.Vec(IDL.Text),
});
export const SalesRecord = IDL.Record({
  'id' : IDL.Nat,
  'totalSalesAmount' : IDL.Nat,
  'accessories' : IDL.Nat,
  'recordDate' : IDL.Int,
  'employeeId' : EmployeeId,
  'extendedWarranty' : IDL.Nat,
  'fiplCode' : IDL.Text,
});
export const TopPerformer = IDL.Record({
  'accessories' : IDL.Nat,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'extendedWarranty' : IDL.Nat,
  'fiplCode' : IDL.Text,
});
export const TopPerformerInput = IDL.Record({
  'accessories' : IDL.Nat,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'extendedWarranty' : IDL.Nat,
  'fiplCode' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAttendanceRecord' : IDL.Func([AttendanceRecordInput], [IDL.Nat], []),
  'addEmployee' : IDL.Func([EmployeeFullInput], [EmployeeId], []),
  'addFeedback' : IDL.Func([FeedbackInput], [IDL.Nat], []),
  'addIssueSuggestion' : IDL.Func([IssueSuggestionInput], [IDL.Nat], []),
  'addSalesRecord' : IDL.Func([SalesRecordInput], [IDL.Nat], []),
  'bulkAddEmployees' : IDL.Func(
      [IDL.Vec(EmployeeInput)],
      [IDL.Vec(EmployeeId)],
      [],
    ),
  'deleteEmployee' : IDL.Func([EmployeeId], [IDL.Bool], []),
  'deleteIssueSuggestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveEmployeeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllIssues' : IDL.Func([], [IDL.Vec(IssueSuggestion)], ['query']),
  'getAttendanceByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getEmployeeDetails' : IDL.Func([EmployeeId], [EmployeeDetails], ['query']),
  'getFeedbackByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'getSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
  'getSalesRecordsByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(SalesRecord)],
      ['query'],
    ),
  'getTopPerformers' : IDL.Func([], [IDL.Vec(TopPerformer)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'setTopPerformers' : IDL.Func([IDL.Vec(TopPerformerInput)], [IDL.Bool], []),
  'updateEmployee' : IDL.Func([EmployeeId, EmployeeFullInput], [IDL.Bool], []),
  'updateEmployeeStatus' : IDL.Func([EmployeeId, Status], [IDL.Bool], []),
  'updateIssueSuggestion' : IDL.Func(
      [IDL.Nat, IssueSuggestionInput],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeId = IDL.Nat;
  const AttendanceRecordInput = IDL.Record({
    'lapseType' : IDL.Text,
    'date' : IDL.Int,
    'employeeId' : EmployeeId,
    'reason' : IDL.Text,
    'daysOff' : IDL.Nat,
  });
  const SWOTInput = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const EmployeeInput = IDL.Record({
    'region' : IDL.Text,
    'status' : Status,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'fseCategory' : IDL.Text,
    'department' : IDL.Text,
    'familyDetails' : IDL.Text,
    'pastExperience' : IDL.Vec(IDL.Text),
    'avatar' : IDL.Text,
    'fiplCode' : IDL.Text,
  });
  const PerformanceInput = IDL.Record({
    'operationalDiscipline' : IDL.Nat,
    'softSkillsScore' : IDL.Nat,
    'productKnowledgeScore' : IDL.Nat,
    'salesInfluenceIndex' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const EmployeeFullInput = IDL.Record({
    'swotAnalysis' : SWOTInput,
    'employeeInfo' : EmployeeInput,
    'traits' : IDL.Vec(IDL.Text),
    'performance' : PerformanceInput,
    'problems' : IDL.Vec(IDL.Text),
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FeedbackInput = IDL.Record({
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'category' : IDL.Text,
    'severity' : Severity,
  });
  const IssueSuggestionInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const SalesRecordInput = IDL.Record({
    'totalSalesAmount' : IDL.Nat,
    'accessories' : IDL.Nat,
    'employeeId' : EmployeeId,
    'extendedWarranty' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'region' : IDL.Text,
    'status' : Status,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'fseCategory' : IDL.Text,
    'department' : IDL.Text,
    'familyDetails' : IDL.Text,
    'pastExperience' : IDL.Vec(IDL.Text),
    'avatar' : IDL.Text,
    'fiplCode' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'category' : IDL.Text,
    'severity' : Severity,
  });
  const IssueSuggestion = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'lapseType' : IDL.Text,
    'date' : IDL.Int,
    'employeeId' : EmployeeId,
    'reason' : IDL.Text,
    'daysOff' : IDL.Nat,
  });
  const SWOT = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
    'employeeId' : EmployeeId,
  });
  const Performance = IDL.Record({
    'operationalDiscipline' : IDL.Nat,
    'softSkillsScore' : IDL.Nat,
    'productKnowledgeScore' : IDL.Nat,
    'salesInfluenceIndex' : IDL.Nat,
    'employeeId' : EmployeeId,
    'reviewCount' : IDL.Nat,
  });
  const EmployeeDetails = IDL.Record({
    'traits' : IDL.Vec(IDL.Text),
    'info' : Employee,
    'swot' : SWOT,
    'performance' : Performance,
    'problems' : IDL.Vec(IDL.Text),
  });
  const SalesRecord = IDL.Record({
    'id' : IDL.Nat,
    'totalSalesAmount' : IDL.Nat,
    'accessories' : IDL.Nat,
    'recordDate' : IDL.Int,
    'employeeId' : EmployeeId,
    'extendedWarranty' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  const TopPerformer = IDL.Record({
    'accessories' : IDL.Nat,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'extendedWarranty' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  const TopPerformerInput = IDL.Record({
    'accessories' : IDL.Nat,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'extendedWarranty' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  
  return IDL.Service({
    'addAttendanceRecord' : IDL.Func([AttendanceRecordInput], [IDL.Nat], []),
    'addEmployee' : IDL.Func([EmployeeFullInput], [EmployeeId], []),
    'addFeedback' : IDL.Func([FeedbackInput], [IDL.Nat], []),
    'addIssueSuggestion' : IDL.Func([IssueSuggestionInput], [IDL.Nat], []),
    'addSalesRecord' : IDL.Func([SalesRecordInput], [IDL.Nat], []),
    'bulkAddEmployees' : IDL.Func(
        [IDL.Vec(EmployeeInput)],
        [IDL.Vec(EmployeeId)],
        [],
      ),
    'deleteEmployee' : IDL.Func([EmployeeId], [IDL.Bool], []),
    'deleteIssueSuggestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveEmployeeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllIssues' : IDL.Func([], [IDL.Vec(IssueSuggestion)], ['query']),
    'getAttendanceByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getEmployeeDetails' : IDL.Func([EmployeeId], [EmployeeDetails], ['query']),
    'getFeedbackByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
    'getSalesRecordsByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(SalesRecord)],
        ['query'],
      ),
    'getTopPerformers' : IDL.Func([], [IDL.Vec(TopPerformer)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'setTopPerformers' : IDL.Func([IDL.Vec(TopPerformerInput)], [IDL.Bool], []),
    'updateEmployee' : IDL.Func(
        [EmployeeId, EmployeeFullInput],
        [IDL.Bool],
        [],
      ),
    'updateEmployeeStatus' : IDL.Func([EmployeeId, Status], [IDL.Bool], []),
    'updateIssueSuggestion' : IDL.Func(
        [IDL.Nat, IssueSuggestionInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };