/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'lapseType' : string,
  'date' : bigint,
  'employeeId' : EmployeeId,
  'remarks' : string,
  'fiplCode' : string,
}
export interface AttendanceRecordInput {
  'lapseType' : string,
  'date' : bigint,
  'employeeId' : EmployeeId,
  'remarks' : string,
  'fiplCode' : string,
}
export interface CallingRecord {
  'id' : bigint,
  'remark' : string,
  'customerName' : string,
  'customerContact' : string,
  'agent' : string,
  'date' : bigint,
  'createdAt' : bigint,
  'callDuration' : string,
  'cesScore' : bigint,
  'notes' : string,
  'brand' : string,
  'outcome' : string,
  'fseName' : string,
  'product' : string,
  'fiplCode' : string,
}
export interface CallingRecordInput {
  'remark' : string,
  'customerName' : string,
  'customerContact' : string,
  'agent' : string,
  'date' : bigint,
  'callDuration' : string,
  'cesScore' : bigint,
  'notes' : string,
  'brand' : string,
  'outcome' : string,
  'fseName' : string,
  'product' : string,
  'fiplCode' : string,
}
export interface CustomerReview {
  'id' : bigint,
  'date' : bigint,
  'createdAt' : bigint,
  'reviewText' : string,
  'reviewerName' : string,
  'rating' : bigint,
  'fseName' : string,
  'fiplCode' : string,
}
export interface CustomerReviewInput {
  'date' : bigint,
  'reviewText' : string,
  'reviewerName' : string,
  'rating' : bigint,
  'fseName' : string,
  'fiplCode' : string,
}
export interface Employee {
  'id' : EmployeeId,
  'region' : string,
  'status' : Status,
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'fseCategory' : string,
  'department' : string,
  'familyDetails' : string,
  'pastExperience' : Array<string>,
  'avatar' : string,
  'fiplCode' : string,
}
export interface EmployeeDetails {
  'traits' : Array<string>,
  'info' : Employee,
  'swot' : SWOT,
  'performance' : Performance,
  'problems' : Array<string>,
}
export interface EmployeeFullInput {
  'swotAnalysis' : SWOTInput,
  'employeeInfo' : EmployeeInput,
  'traits' : Array<string>,
  'performance' : PerformanceInput,
  'problems' : Array<string>,
}
export type EmployeeId = bigint;
export interface EmployeeInput {
  'region' : string,
  'status' : Status,
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'fseCategory' : string,
  'department' : string,
  'familyDetails' : string,
  'pastExperience' : Array<string>,
  'avatar' : string,
  'fiplCode' : string,
}
export interface Feedback {
  'id' : bigint,
  'date' : bigint,
  'description' : string,
  'employeeId' : EmployeeId,
  'category' : string,
  'severity' : Severity,
}
export interface FeedbackInput {
  'description' : string,
  'employeeId' : EmployeeId,
  'category' : string,
  'severity' : Severity,
}
export interface IssueSuggestion {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'category' : string,
}
export interface IssueSuggestionInput {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface Performance {
  'operationalDiscipline' : bigint,
  'softSkillsScore' : bigint,
  'productKnowledgeScore' : bigint,
  'salesInfluenceIndex' : bigint,
  'employeeId' : EmployeeId,
  'reviewCount' : bigint,
}
export interface PerformanceInput {
  'operationalDiscipline' : bigint,
  'softSkillsScore' : bigint,
  'productKnowledgeScore' : bigint,
  'salesInfluenceIndex' : bigint,
  'reviewCount' : bigint,
}
export interface SWOT {
  'weaknesses' : Array<string>,
  'strengths' : Array<string>,
  'threats' : Array<string>,
  'opportunities' : Array<string>,
  'cesScore' : bigint,
  'employeeId' : EmployeeId,
}
export interface SWOTInput {
  'weaknesses' : Array<string>,
  'strengths' : Array<string>,
  'threats' : Array<string>,
  'opportunities' : Array<string>,
  'cesScore' : bigint,
}
export type SaleType = { 'accessories' : null } |
  { 'extendedWarranty' : null };
export type SalesBrand = { 'tineco' : null } |
  { 'ecovacs' : null } |
  { 'coway' : null } |
  { 'kuvings' : null } |
  { 'instant' : null };
export interface SalesRecord {
  'id' : bigint,
  'saleType' : SaleType,
  'recordDate' : bigint,
  'employeeId' : EmployeeId,
  'quantity' : bigint,
  'brand' : SalesBrand,
  'amount' : bigint,
  'product' : string,
  'saleDate' : bigint,
  'fiplCode' : string,
}
export interface SalesRecordInput {
  'saleType' : SaleType,
  'employeeId' : EmployeeId,
  'quantity' : bigint,
  'brand' : SalesBrand,
  'amount' : bigint,
  'product' : string,
  'saleDate' : bigint,
  'fiplCode' : string,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Status = { 'active' : null } |
  { 'inactive' : null } |
  { 'onHold' : null };
export interface SwotBatchInput {
  'traits' : Array<string>,
  'swot' : SWOTInput,
  'problems' : Array<string>,
  'fiplCode' : string,
}
export interface TopPerformer {
  'accessories' : bigint,
  'name' : string,
  'rank' : bigint,
  'totalSales' : bigint,
  'extendedWarranty' : bigint,
  'fiplCode' : string,
}
export interface TopPerformerInput {
  'accessories' : bigint,
  'name' : string,
  'rank' : bigint,
  'totalSales' : bigint,
  'extendedWarranty' : bigint,
  'fiplCode' : string,
}
export interface _SERVICE {
  'addAttendanceRecord' : ActorMethod<[AttendanceRecordInput], bigint>,
  'addAttendanceRecordsBatch' : ActorMethod<
    [Array<AttendanceRecordInput>],
    Array<bigint>
  >,
  'addCallingRecord' : ActorMethod<[CallingRecordInput], bigint>,
  'addCallingRecordsBatch' : ActorMethod<
    [Array<CallingRecordInput>],
    Array<bigint>
  >,
  'addCustomerReview' : ActorMethod<[CustomerReviewInput], bigint>,
  'addEmployee' : ActorMethod<[EmployeeFullInput], EmployeeId>,
  'addFeedback' : ActorMethod<[FeedbackInput], bigint>,
  'addIssueSuggestion' : ActorMethod<[IssueSuggestionInput], bigint>,
  'addProblem' : ActorMethod<[EmployeeId, string], boolean>,
  'addSalesRecord' : ActorMethod<[SalesRecordInput], bigint>,
  'addSalesRecordsBatch' : ActorMethod<
    [Array<SalesRecordInput>],
    Array<bigint>
  >,
  'addTrait' : ActorMethod<[EmployeeId, string], boolean>,
  'bulkAddEmployees' : ActorMethod<[Array<EmployeeInput>], Array<EmployeeId>>,
  'clearAllAttendance' : ActorMethod<[], boolean>,
  'clearAllCallingRecords' : ActorMethod<[], boolean>,
  'clearAllCustomerReviews' : ActorMethod<[], boolean>,
  'clearAllData' : ActorMethod<[], boolean>,
  'clearAllEmployees' : ActorMethod<[], boolean>,
  'clearAllFeedback' : ActorMethod<[], boolean>,
  'clearAllIssues' : ActorMethod<[], boolean>,
  'clearAllSalesRecords' : ActorMethod<[], boolean>,
  'clearAllTopPerformers' : ActorMethod<[], boolean>,
  'deleteCustomerReview' : ActorMethod<[bigint], boolean>,
  'deleteEmployee' : ActorMethod<[EmployeeId], boolean>,
  'deleteIssueSuggestion' : ActorMethod<[bigint], boolean>,
  'getActiveEmployeeCount' : ActorMethod<[], bigint>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllCallingRecords' : ActorMethod<[], Array<CallingRecord>>,
  'getAllCustomerReviews' : ActorMethod<[], Array<CustomerReview>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllIssues' : ActorMethod<[], Array<IssueSuggestion>>,
  'getAttendanceByEmployee' : ActorMethod<
    [EmployeeId],
    Array<AttendanceRecord>
  >,
  'getEmployeeDetails' : ActorMethod<[EmployeeId], EmployeeDetails>,
  'getFeedbackByEmployee' : ActorMethod<[EmployeeId], Array<Feedback>>,
  'getSalesRecords' : ActorMethod<[], Array<SalesRecord>>,
  'getSalesRecordsByEmployee' : ActorMethod<[EmployeeId], Array<SalesRecord>>,
  'getTopPerformers' : ActorMethod<[], Array<TopPerformer>>,
  'initialize' : ActorMethod<[], undefined>,
  'setTopPerformers' : ActorMethod<[Array<TopPerformerInput>], boolean>,
  'updateEmployee' : ActorMethod<[EmployeeId, EmployeeFullInput], boolean>,
  'updateEmployeePerformance' : ActorMethod<
    [EmployeeId, PerformanceInput],
    boolean
  >,
  'updateEmployeeSWOT' : ActorMethod<[EmployeeId, SWOTInput], boolean>,
  'updateEmployeeStatus' : ActorMethod<[EmployeeId, Status], boolean>,
  'updateIssueSuggestion' : ActorMethod<
    [bigint, IssueSuggestionInput],
    boolean
  >,
  'updatePerformanceBatch' : ActorMethod<
    [Array<[string, PerformanceInput]>],
    bigint
  >,
  'updatePerformanceByFiplCode' : ActorMethod<
    [string, PerformanceInput],
    boolean
  >,
  'updateSwotBatch' : ActorMethod<[Array<SwotBatchInput>], bigint>,
  'updateSwotByFiplCode' : ActorMethod<
    [string, SWOTInput, Array<string>, Array<string>],
    boolean
  >,
  'upsertEmployeesBatch' : ActorMethod<
    [Array<EmployeeFullInput>],
    Array<[string, EmployeeId]>
  >,
  'getAppSettings' : ActorMethod<[], string>,
  'setAppSettings' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];