/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SWOTInput = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'onHold' : IDL.Null,
});
export const EmployeeInput = IDL.Record({
  'status' : Status,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'department' : IDL.Text,
  'avatar' : IDL.Text,
});
export const PerformanceInput = IDL.Record({
  'opsScore' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'salesScore' : IDL.Nat,
});
export const EmployeeFullInput = IDL.Record({
  'swotAnalysis' : SWOTInput,
  'employeeInfo' : EmployeeInput,
  'traits' : IDL.Vec(IDL.Text),
  'performance' : PerformanceInput,
  'problems' : IDL.Vec(IDL.Text),
});
export const EmployeeId = IDL.Nat;
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FeedbackInput = IDL.Record({
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'category' : IDL.Text,
  'severity' : Severity,
});
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'status' : Status,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'department' : IDL.Text,
  'avatar' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'category' : IDL.Text,
  'severity' : Severity,
});
export const SWOT = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
  'employeeId' : EmployeeId,
});
export const Performance = IDL.Record({
  'opsScore' : IDL.Nat,
  'employeeId' : EmployeeId,
  'reviewCount' : IDL.Nat,
  'salesScore' : IDL.Nat,
});
export const EmployeeDetails = IDL.Record({
  'traits' : IDL.Vec(IDL.Text),
  'info' : Employee,
  'swot' : SWOT,
  'performance' : Performance,
  'problems' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func([EmployeeFullInput], [EmployeeId], []),
  'addFeedback' : IDL.Func([FeedbackInput], [IDL.Nat], []),
  'bulkAddEmployees' : IDL.Func(
      [IDL.Vec(EmployeeInput)],
      [IDL.Vec(EmployeeId)],
      [],
    ),
  'deleteEmployee' : IDL.Func([EmployeeId], [IDL.Bool], []),
  'getActiveEmployeeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getEmployeeDetails' : IDL.Func([EmployeeId], [EmployeeDetails], ['query']),
  'getFeedbackByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'updateEmployee' : IDL.Func([EmployeeId, EmployeeFullInput], [IDL.Bool], []),
  'updateEmployeeStatus' : IDL.Func([EmployeeId, Status], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SWOTInput = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const EmployeeInput = IDL.Record({
    'status' : Status,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'department' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const PerformanceInput = IDL.Record({
    'opsScore' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'salesScore' : IDL.Nat,
  });
  const EmployeeFullInput = IDL.Record({
    'swotAnalysis' : SWOTInput,
    'employeeInfo' : EmployeeInput,
    'traits' : IDL.Vec(IDL.Text),
    'performance' : PerformanceInput,
    'problems' : IDL.Vec(IDL.Text),
  });
  const EmployeeId = IDL.Nat;
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FeedbackInput = IDL.Record({
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'category' : IDL.Text,
    'severity' : Severity,
  });
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'status' : Status,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'department' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'category' : IDL.Text,
    'severity' : Severity,
  });
  const SWOT = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
    'employeeId' : EmployeeId,
  });
  const Performance = IDL.Record({
    'opsScore' : IDL.Nat,
    'employeeId' : EmployeeId,
    'reviewCount' : IDL.Nat,
    'salesScore' : IDL.Nat,
  });
  const EmployeeDetails = IDL.Record({
    'traits' : IDL.Vec(IDL.Text),
    'info' : Employee,
    'swot' : SWOT,
    'performance' : Performance,
    'problems' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addEmployee' : IDL.Func([EmployeeFullInput], [EmployeeId], []),
    'addFeedback' : IDL.Func([FeedbackInput], [IDL.Nat], []),
    'bulkAddEmployees' : IDL.Func(
        [IDL.Vec(EmployeeInput)],
        [IDL.Vec(EmployeeId)],
        [],
      ),
    'deleteEmployee' : IDL.Func([EmployeeId], [IDL.Bool], []),
    'getActiveEmployeeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getEmployeeDetails' : IDL.Func([EmployeeId], [EmployeeDetails], ['query']),
    'getFeedbackByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'updateEmployee' : IDL.Func(
        [EmployeeId, EmployeeFullInput],
        [IDL.Bool],
        [],
      ),
    'updateEmployeeStatus' : IDL.Func([EmployeeId, Status], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };