/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SWOT {
    weaknesses: Array<string>;
    strengths: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
    employeeId: EmployeeId;
}
export interface SWOTInput {
    weaknesses: Array<string>;
    strengths: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
}
export interface Employee {
    id: EmployeeId;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
}
export type EmployeeId = bigint;
export interface Feedback {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}
export interface Performance {
    opsScore: bigint;
    employeeId: EmployeeId;
    reviewCount: bigint;
    salesScore: bigint;
}
export interface EmployeeDetails {
    traits: Array<string>;
    info: Employee;
    swot: SWOT;
    performance: Performance;
    problems: Array<string>;
}
export interface PerformanceInput {
    opsScore: bigint;
    reviewCount: bigint;
    salesScore: bigint;
}
export interface FeedbackInput {
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}
export interface EmployeeFullInput {
    swotAnalysis: SWOTInput;
    employeeInfo: EmployeeInput;
    traits: Array<string>;
    performance: PerformanceInput;
    problems: Array<string>;
}
export interface EmployeeInput {
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
}
export enum Severity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    active = "active",
    inactive = "inactive",
    onHold = "onHold"
}
export interface backendInterface {
    addEmployee(employeeInput: EmployeeFullInput): Promise<EmployeeId>;
    addFeedback(feedbackInput: FeedbackInput): Promise<bigint>;
    bulkAddEmployees(basicInputs: Array<EmployeeInput>): Promise<Array<EmployeeId>>;
    deleteEmployee(id: EmployeeId): Promise<boolean>;
    getActiveEmployeeCount(): Promise<bigint>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getEmployeeDetails(id: EmployeeId): Promise<EmployeeDetails>;
    getFeedbackByEmployee(employeeId: EmployeeId): Promise<Array<Feedback>>;
    initialize(): Promise<void>;
    updateEmployee(id: EmployeeId, input: EmployeeFullInput): Promise<boolean>;
    updateEmployeeStatus(id: EmployeeId, newStatus: Status): Promise<boolean>;
}
import type { Employee as _Employee, EmployeeDetails as _EmployeeDetails, EmployeeFullInput as _EmployeeFullInput, EmployeeId as _EmployeeId, EmployeeInput as _EmployeeInput, Feedback as _Feedback, FeedbackInput as _FeedbackInput, Performance as _Performance, PerformanceInput as _PerformanceInput, SWOT as _SWOT, SWOTInput as _SWOTInput, Severity as _Severity, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmployee(arg0: EmployeeFullInput): Promise<EmployeeId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFeedback(arg0: FeedbackInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedback(to_candid_FeedbackInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedback(to_candid_FeedbackInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkAddEmployees(arg0: Array<EmployeeInput>): Promise<Array<EmployeeId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddEmployees(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddEmployees(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteEmployee(arg0: EmployeeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getActiveEmployeeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveEmployeeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveEmployeeCount();
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeDetails(arg0: EmployeeId): Promise<EmployeeDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeDetails(arg0);
                return from_candid_EmployeeDetails_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeDetails(arg0);
            return from_candid_EmployeeDetails_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackByEmployee(arg0: EmployeeId): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackByEmployee(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackByEmployee(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async updateEmployee(arg0: EmployeeId, arg1: EmployeeFullInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployeeStatus(arg0: EmployeeId, arg1: Status): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeStatus(arg0, to_candid_Status_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeStatus(arg0, to_candid_Status_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EmployeeDetails_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeDetails): EmployeeDetails {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Feedback_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeId;
    status: _Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
}): {
    id: EmployeeId;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n15(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        department: value.department,
        avatar: value.avatar
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: _EmployeeId;
    category: string;
    severity: _Severity;
}): {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        employeeId: value.employeeId,
        category: value.category,
        severity: from_candid_Severity_n20(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    traits: Array<string>;
    info: _Employee;
    swot: _SWOT;
    performance: _Performance;
    problems: Array<string>;
}): {
    traits: Array<string>;
    info: Employee;
    swot: SWOT;
    performance: Performance;
    problems: Array<string>;
} {
    return {
        traits: value.traits,
        info: from_candid_Employee_n13(_uploadFile, _downloadFile, value.info),
        swot: value.swot,
        performance: value.performance,
        problems: value.problems
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    onHold: null;
}): Status {
    return "active" in value ? Status.active : "inactive" in value ? Status.inactive : "onHold" in value ? Status.onHold : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "medium" in value ? Severity.medium : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n18(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeFullInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeFullInput): _EmployeeFullInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeInput): _EmployeeInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FeedbackInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackInput): _FeedbackInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    swotAnalysis: SWOTInput;
    employeeInfo: EmployeeInput;
    traits: Array<string>;
    performance: PerformanceInput;
    problems: Array<string>;
}): {
    swotAnalysis: _SWOTInput;
    employeeInfo: _EmployeeInput;
    traits: Array<string>;
    performance: _PerformanceInput;
    problems: Array<string>;
} {
    return {
        swotAnalysis: value.swotAnalysis,
        employeeInfo: to_candid_EmployeeInput_n3(_uploadFile, _downloadFile, value.employeeInfo),
        traits: value.traits,
        performance: value.performance,
        problems: value.problems
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
}): {
    status: _Status;
    joinDate: bigint;
    name: string;
    role: string;
    department: string;
    avatar: string;
} {
    return {
        status: to_candid_Status_n5(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        department: value.department,
        avatar: value.avatar
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}): {
    description: string;
    employeeId: _EmployeeId;
    category: string;
    severity: _Severity;
} {
    return {
        description: value.description,
        employeeId: value.employeeId,
        category: value.category,
        severity: to_candid_Severity_n9(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    inactive: null;
} | {
    onHold: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.inactive ? {
        inactive: null
    } : value == Status.onHold ? {
        onHold: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmployeeInput>): Array<_EmployeeInput> {
    return value.map((x)=>to_candid_EmployeeInput_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
