/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SWOT {
    weaknesses: Array<string>;
    strengths: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
    cesScore: bigint;
    employeeId: EmployeeId;
}
export interface IssueSuggestionInput {
    title: string;
    description: string;
    category: string;
}
export interface SalesRecordInput {
    saleType: SaleType;
    employeeId: EmployeeId;
    quantity: bigint;
    brand: SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
}
export interface Feedback {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}
export interface IssueSuggestion {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    category: string;
}
export interface TopPerformerInput {
    accessories: bigint;
    name: string;
    rank: bigint;
    totalSales: bigint;
    extendedWarranty: bigint;
    fiplCode: string;
}
export interface SwotBatchInput {
    traits: Array<string>;
    swot: SWOTInput;
    problems: Array<string>;
    fiplCode: string;
}
export interface SalesRecord {
    id: bigint;
    saleType: SaleType;
    recordDate: bigint;
    employeeId: EmployeeId;
    quantity: bigint;
    brand: SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
}
export interface PerformanceInput {
    operationalDiscipline: bigint;
    softSkillsScore: bigint;
    productKnowledgeScore: bigint;
    salesInfluenceIndex: bigint;
    reviewCount: bigint;
}
export interface CustomerReview {
    id: bigint;
    date: bigint;
    createdAt: bigint;
    reviewText: string;
    reviewerName: string;
    rating: bigint;
    fseName: string;
    fiplCode: string;
}
export interface SWOTInput {
    weaknesses: Array<string>;
    strengths: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
    cesScore: bigint;
}
export type EmployeeId = bigint;
export interface Employee {
    id: EmployeeId;
    region: string;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
}
export interface AttendanceRecord {
    id: bigint;
    lapseType: string;
    date: bigint;
    employeeId: EmployeeId;
    reason: string;
    daysOff: bigint;
}
export interface Performance {
    operationalDiscipline: bigint;
    softSkillsScore: bigint;
    productKnowledgeScore: bigint;
    salesInfluenceIndex: bigint;
    employeeId: EmployeeId;
    reviewCount: bigint;
}
export interface EmployeeFullInput {
    swotAnalysis: SWOTInput;
    employeeInfo: EmployeeInput;
    traits: Array<string>;
    performance: PerformanceInput;
    problems: Array<string>;
}
export interface CallingRecord {
    id: bigint;
    remark: string;
    customerName: string;
    customerContact: string;
    agent: string;
    date: bigint;
    createdAt: bigint;
    callDuration: string;
    cesScore: bigint;
    notes: string;
    brand: string;
    outcome: string;
    fseName: string;
    product: string;
    fiplCode: string;
}
export interface CustomerReviewInput {
    date: bigint;
    reviewText: string;
    reviewerName: string;
    rating: bigint;
    fseName: string;
    fiplCode: string;
}
export interface CallingRecordInput {
    remark: string;
    customerName: string;
    customerContact: string;
    agent: string;
    date: bigint;
    callDuration: string;
    cesScore: bigint;
    notes: string;
    brand: string;
    outcome: string;
    fseName: string;
    product: string;
    fiplCode: string;
}
export interface AttendanceRecordInput {
    lapseType: string;
    date: bigint;
    employeeId: EmployeeId;
    reason: string;
    daysOff: bigint;
}
export interface TopPerformer {
    accessories: bigint;
    name: string;
    rank: bigint;
    totalSales: bigint;
    extendedWarranty: bigint;
    fiplCode: string;
}
export interface EmployeeDetails {
    traits: Array<string>;
    info: Employee;
    swot: SWOT;
    performance: Performance;
    problems: Array<string>;
}
export interface FeedbackInput {
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}
export interface EmployeeInput {
    region: string;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
}
export enum SaleType {
    accessories = "accessories",
    extendedWarranty = "extendedWarranty"
}
export enum SalesBrand {
    tineco = "tineco",
    ecovacs = "ecovacs",
    coway = "coway",
    kuvings = "kuvings",
    instant = "instant"
}
export enum Severity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    active = "active",
    inactive = "inactive",
    onHold = "onHold"
}
export interface backendInterface {
    addAttendanceRecord(input: AttendanceRecordInput): Promise<bigint>;
    addAttendanceRecordsBatch(inputs: Array<AttendanceRecordInput>): Promise<Array<bigint>>;
    addCallingRecord(input: CallingRecordInput): Promise<bigint>;
    addCallingRecordsBatch(inputs: Array<CallingRecordInput>): Promise<Array<bigint>>;
    addCustomerReview(input: CustomerReviewInput): Promise<bigint>;
    addEmployee(input: EmployeeFullInput): Promise<EmployeeId>;
    addFeedback(input: FeedbackInput): Promise<bigint>;
    addIssueSuggestion(input: IssueSuggestionInput): Promise<bigint>;
    addProblem(employeeId: EmployeeId, problem: string): Promise<boolean>;
    addSalesRecord(input: SalesRecordInput): Promise<bigint>;
    addSalesRecordsBatch(inputs: Array<SalesRecordInput>): Promise<Array<bigint>>;
    addTrait(employeeId: EmployeeId, trait: string): Promise<boolean>;
    bulkAddEmployees(inputs: Array<EmployeeInput>): Promise<Array<EmployeeId>>;
    clearAllAttendance(): Promise<boolean>;
    clearAllCallingRecords(): Promise<boolean>;
    clearAllCustomerReviews(): Promise<boolean>;
    clearAllData(): Promise<boolean>;
    clearAllEmployees(): Promise<boolean>;
    clearAllFeedback(): Promise<boolean>;
    clearAllIssues(): Promise<boolean>;
    clearAllSalesRecords(): Promise<boolean>;
    clearAllTopPerformers(): Promise<boolean>;
    deleteCustomerReview(id: bigint): Promise<boolean>;
    deleteEmployee(id: EmployeeId): Promise<boolean>;
    deleteIssueSuggestion(id: bigint): Promise<boolean>;
    getActiveEmployeeCount(): Promise<bigint>;
    getAllCallingRecords(): Promise<Array<CallingRecord>>;
    getAllCustomerReviews(): Promise<Array<CustomerReview>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllIssues(): Promise<Array<IssueSuggestion>>;
    getAttendanceByEmployee(employeeId: EmployeeId): Promise<Array<AttendanceRecord>>;
    getEmployeeDetails(id: EmployeeId): Promise<EmployeeDetails>;
    getFeedbackByEmployee(employeeId: EmployeeId): Promise<Array<Feedback>>;
    getSalesRecords(): Promise<Array<SalesRecord>>;
    getSalesRecordsByEmployee(employeeId: EmployeeId): Promise<Array<SalesRecord>>;
    getTopPerformers(): Promise<Array<TopPerformer>>;
    initialize(): Promise<void>;
    setTopPerformers(inputs: Array<TopPerformerInput>): Promise<boolean>;
    updateEmployee(id: EmployeeId, input: EmployeeFullInput): Promise<boolean>;
    updateEmployeePerformance(employeeId: EmployeeId, input: PerformanceInput): Promise<boolean>;
    updateEmployeeSWOT(employeeId: EmployeeId, swotInput: SWOTInput): Promise<boolean>;
    updateEmployeeStatus(id: EmployeeId, newStatus: Status): Promise<boolean>;
    updateIssueSuggestion(id: bigint, input: IssueSuggestionInput): Promise<boolean>;
    updatePerformanceBatch(inputs: Array<[string, PerformanceInput]>): Promise<bigint>;
    updatePerformanceByFiplCode(fiplCode: string, input: PerformanceInput): Promise<boolean>;
    updateSwotBatch(inputs: Array<SwotBatchInput>): Promise<bigint>;
    updateSwotByFiplCode(fiplCode: string, swotInput: SWOTInput, newTraits: Array<string>, newProblems: Array<string>): Promise<boolean>;
    upsertEmployeesBatch(inputs: Array<EmployeeFullInput>): Promise<Array<[string, EmployeeId]>>;
}
import type { Employee as _Employee, EmployeeDetails as _EmployeeDetails, EmployeeFullInput as _EmployeeFullInput, EmployeeId as _EmployeeId, EmployeeInput as _EmployeeInput, Feedback as _Feedback, FeedbackInput as _FeedbackInput, Performance as _Performance, PerformanceInput as _PerformanceInput, SWOT as _SWOT, SWOTInput as _SWOTInput, SaleType as _SaleType, SalesBrand as _SalesBrand, SalesRecord as _SalesRecord, SalesRecordInput as _SalesRecordInput, Severity as _Severity, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAttendanceRecord(arg0: AttendanceRecordInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendanceRecord(arg0);
            return result;
        }
    }
    async addAttendanceRecordsBatch(arg0: Array<AttendanceRecordInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendanceRecordsBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendanceRecordsBatch(arg0);
            return result;
        }
    }
    async addCallingRecord(arg0: CallingRecordInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallingRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallingRecord(arg0);
            return result;
        }
    }
    async addCallingRecordsBatch(arg0: Array<CallingRecordInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallingRecordsBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallingRecordsBatch(arg0);
            return result;
        }
    }
    async addCustomerReview(arg0: CustomerReviewInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomerReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomerReview(arg0);
            return result;
        }
    }
    async addEmployee(arg0: EmployeeFullInput): Promise<EmployeeId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFeedback(arg0: FeedbackInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedback(to_candid_FeedbackInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedback(to_candid_FeedbackInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addIssueSuggestion(arg0: IssueSuggestionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIssueSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIssueSuggestion(arg0);
            return result;
        }
    }
    async addProblem(arg0: EmployeeId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addProblem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProblem(arg0, arg1);
            return result;
        }
    }
    async addSalesRecord(arg0: SalesRecordInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesRecord(to_candid_SalesRecordInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesRecord(to_candid_SalesRecordInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSalesRecordsBatch(arg0: Array<SalesRecordInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesRecordsBatch(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesRecordsBatch(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrait(arg0: EmployeeId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrait(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrait(arg0, arg1);
            return result;
        }
    }
    async bulkAddEmployees(arg0: Array<EmployeeInput>): Promise<Array<EmployeeId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddEmployees(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddEmployees(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAllAttendance(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllAttendance();
            return result;
        }
    }
    async clearAllCallingRecords(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllCallingRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllCallingRecords();
            return result;
        }
    }
    async clearAllCustomerReviews(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllCustomerReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllCustomerReviews();
            return result;
        }
    }
    async clearAllData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async clearAllEmployees(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllEmployees();
            return result;
        }
    }
    async clearAllFeedback(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllFeedback();
            return result;
        }
    }
    async clearAllIssues(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllIssues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllIssues();
            return result;
        }
    }
    async clearAllSalesRecords(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllSalesRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllSalesRecords();
            return result;
        }
    }
    async clearAllTopPerformers(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllTopPerformers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllTopPerformers();
            return result;
        }
    }
    async deleteCustomerReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerReview(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: EmployeeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteIssueSuggestion(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIssueSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIssueSuggestion(arg0);
            return result;
        }
    }
    async getActiveEmployeeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveEmployeeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveEmployeeCount();
            return result;
        }
    }
    async getAllCallingRecords(): Promise<Array<CallingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCallingRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCallingRecords();
            return result;
        }
    }
    async getAllCustomerReviews(): Promise<Array<CustomerReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomerReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomerReviews();
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIssues(): Promise<Array<IssueSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIssues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIssues();
            return result;
        }
    }
    async getAttendanceByEmployee(arg0: EmployeeId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByEmployee(arg0);
            return result;
        }
    }
    async getEmployeeDetails(arg0: EmployeeId): Promise<EmployeeDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeDetails(arg0);
                return from_candid_EmployeeDetails_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeDetails(arg0);
            return from_candid_EmployeeDetails_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackByEmployee(arg0: EmployeeId): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackByEmployee(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackByEmployee(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesRecords(): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecords();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecords();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesRecordsByEmployee(arg0: EmployeeId): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecordsByEmployee(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecordsByEmployee(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopPerformers(): Promise<Array<TopPerformer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPerformers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPerformers();
            return result;
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async setTopPerformers(arg0: Array<TopPerformerInput>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTopPerformers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTopPerformers(arg0);
            return result;
        }
    }
    async updateEmployee(arg0: EmployeeId, arg1: EmployeeFullInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeFullInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployeePerformance(arg0: EmployeeId, arg1: PerformanceInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeePerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeePerformance(arg0, arg1);
            return result;
        }
    }
    async updateEmployeeSWOT(arg0: EmployeeId, arg1: SWOTInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeSWOT(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeSWOT(arg0, arg1);
            return result;
        }
    }
    async updateEmployeeStatus(arg0: EmployeeId, arg1: Status): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeStatus(arg0, to_candid_Status_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeStatus(arg0, to_candid_Status_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateIssueSuggestion(arg0: bigint, arg1: IssueSuggestionInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIssueSuggestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIssueSuggestion(arg0, arg1);
            return result;
        }
    }
    async updatePerformanceBatch(arg0: Array<[string, PerformanceInput]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerformanceBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerformanceBatch(arg0);
            return result;
        }
    }
    async updatePerformanceByFiplCode(arg0: string, arg1: PerformanceInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerformanceByFiplCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerformanceByFiplCode(arg0, arg1);
            return result;
        }
    }
    async updateSwotBatch(arg0: Array<SwotBatchInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSwotBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSwotBatch(arg0);
            return result;
        }
    }
    async updateSwotByFiplCode(arg0: string, arg1: SWOTInput, arg2: Array<string>, arg3: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSwotByFiplCode(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSwotByFiplCode(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async upsertEmployeesBatch(arg0: Array<EmployeeFullInput>): Promise<Array<[string, EmployeeId]>> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertEmployeesBatch(to_candid_vec_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertEmployeesBatch(to_candid_vec_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_EmployeeDetails_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeDetails): EmployeeDetails {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Feedback_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SaleType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleType): SaleType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SalesBrand_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesBrand): SalesBrand {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SalesRecord_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesRecord): SalesRecord {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeId;
    region: string;
    status: _Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
}): {
    id: EmployeeId;
    region: string;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
} {
    return {
        id: value.id,
        region: value.region,
        status: from_candid_Status_n22(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        fseCategory: value.fseCategory,
        department: value.department,
        familyDetails: value.familyDetails,
        pastExperience: value.pastExperience,
        avatar: value.avatar,
        fiplCode: value.fiplCode
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: _EmployeeId;
    category: string;
    severity: _Severity;
}): {
    id: bigint;
    date: bigint;
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        employeeId: value.employeeId,
        category: value.category,
        severity: from_candid_Severity_n27(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    traits: Array<string>;
    info: _Employee;
    swot: _SWOT;
    performance: _Performance;
    problems: Array<string>;
}): {
    traits: Array<string>;
    info: Employee;
    swot: SWOT;
    performance: Performance;
    problems: Array<string>;
} {
    return {
        traits: value.traits,
        info: from_candid_Employee_n20(_uploadFile, _downloadFile, value.info),
        swot: value.swot,
        performance: value.performance,
        problems: value.problems
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    saleType: _SaleType;
    recordDate: bigint;
    employeeId: _EmployeeId;
    quantity: bigint;
    brand: _SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
}): {
    id: bigint;
    saleType: SaleType;
    recordDate: bigint;
    employeeId: EmployeeId;
    quantity: bigint;
    brand: SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
} {
    return {
        id: value.id,
        saleType: from_candid_SaleType_n34(_uploadFile, _downloadFile, value.saleType),
        recordDate: value.recordDate,
        employeeId: value.employeeId,
        quantity: value.quantity,
        brand: from_candid_SalesBrand_n36(_uploadFile, _downloadFile, value.brand),
        amount: value.amount,
        product: value.product,
        saleDate: value.saleDate,
        fiplCode: value.fiplCode
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    onHold: null;
}): Status {
    return "active" in value ? Status.active : "inactive" in value ? Status.inactive : "onHold" in value ? Status.onHold : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessories: null;
} | {
    extendedWarranty: null;
}): SaleType {
    return "accessories" in value ? SaleType.accessories : "extendedWarranty" in value ? SaleType.extendedWarranty : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tineco: null;
} | {
    ecovacs: null;
} | {
    coway: null;
} | {
    kuvings: null;
} | {
    instant: null;
}): SalesBrand {
    return "tineco" in value ? SalesBrand.tineco : "ecovacs" in value ? SalesBrand.ecovacs : "coway" in value ? SalesBrand.coway : "kuvings" in value ? SalesBrand.kuvings : "instant" in value ? SalesBrand.instant : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesRecord>): Array<SalesRecord> {
    return value.map((x)=>from_candid_SalesRecord_n32(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeFullInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeFullInput): _EmployeeFullInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeInput): _EmployeeInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FeedbackInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackInput): _FeedbackInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SaleType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleType): _SaleType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SalesBrand_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesBrand): _SalesBrand {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SalesRecordInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesRecordInput): _SalesRecordInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saleType: SaleType;
    employeeId: EmployeeId;
    quantity: bigint;
    brand: SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
}): {
    saleType: _SaleType;
    employeeId: _EmployeeId;
    quantity: bigint;
    brand: _SalesBrand;
    amount: bigint;
    product: string;
    saleDate: bigint;
    fiplCode: string;
} {
    return {
        saleType: to_candid_SaleType_n13(_uploadFile, _downloadFile, value.saleType),
        employeeId: value.employeeId,
        quantity: value.quantity,
        brand: to_candid_SalesBrand_n15(_uploadFile, _downloadFile, value.brand),
        amount: value.amount,
        product: value.product,
        saleDate: value.saleDate,
        fiplCode: value.fiplCode
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    swotAnalysis: SWOTInput;
    employeeInfo: EmployeeInput;
    traits: Array<string>;
    performance: PerformanceInput;
    problems: Array<string>;
}): {
    swotAnalysis: _SWOTInput;
    employeeInfo: _EmployeeInput;
    traits: Array<string>;
    performance: _PerformanceInput;
    problems: Array<string>;
} {
    return {
        swotAnalysis: value.swotAnalysis,
        employeeInfo: to_candid_EmployeeInput_n3(_uploadFile, _downloadFile, value.employeeInfo),
        traits: value.traits,
        performance: value.performance,
        problems: value.problems
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    status: Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
}): {
    region: string;
    status: _Status;
    joinDate: bigint;
    name: string;
    role: string;
    fseCategory: string;
    department: string;
    familyDetails: string;
    pastExperience: Array<string>;
    avatar: string;
    fiplCode: string;
} {
    return {
        region: value.region,
        status: to_candid_Status_n5(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        fseCategory: value.fseCategory,
        department: value.department,
        familyDetails: value.familyDetails,
        pastExperience: value.pastExperience,
        avatar: value.avatar,
        fiplCode: value.fiplCode
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    employeeId: EmployeeId;
    category: string;
    severity: Severity;
}): {
    description: string;
    employeeId: _EmployeeId;
    category: string;
    severity: _Severity;
} {
    return {
        description: value.description,
        employeeId: value.employeeId,
        category: value.category,
        severity: to_candid_Severity_n9(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleType): {
    accessories: null;
} | {
    extendedWarranty: null;
} {
    return value == SaleType.accessories ? {
        accessories: null
    } : value == SaleType.extendedWarranty ? {
        extendedWarranty: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesBrand): {
    tineco: null;
} | {
    ecovacs: null;
} | {
    coway: null;
} | {
    kuvings: null;
} | {
    instant: null;
} {
    return value == SalesBrand.tineco ? {
        tineco: null
    } : value == SalesBrand.ecovacs ? {
        ecovacs: null
    } : value == SalesBrand.coway ? {
        coway: null
    } : value == SalesBrand.kuvings ? {
        kuvings: null
    } : value == SalesBrand.instant ? {
        instant: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    inactive: null;
} | {
    onHold: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.inactive ? {
        inactive: null
    } : value == Status.onHold ? {
        onHold: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SalesRecordInput>): Array<_SalesRecordInput> {
    return value.map((x)=>to_candid_SalesRecordInput_n11(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmployeeInput>): Array<_EmployeeInput> {
    return value.map((x)=>to_candid_EmployeeInput_n3(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmployeeFullInput>): Array<_EmployeeFullInput> {
    return value.map((x)=>to_candid_EmployeeFullInput_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
